## HW 3a: Implement Perceptron for Heart Disease

1. Use step function and $\eta = 0.1$ and batch size = 4 (ok to use 1 if need be)
2. Use TUNE set to choose ‘early stopping’ epoch for each of 10 test folds (maxEpochs = 10,000 but can stop if / when all trainset examples correct)
3. Ok to just use ONE tune set (but feel free to use 9 as done in HW1 and HW2)
4. Once epochsToUse estimated, train on all 9 folds; use (8/9) epochsToUse
5. Report best epoch and min, mean, and max accuracy per train-tune fold 
6. Compare to Random Forests and kNN test set min, mean, and max

In [61]:
import numpy as np

def step_function(x: int):
    return 1 if x >= 0 else 0

class Perceptron:
    def __init__(self, num_weights, activation_function, learning_rate=0.1):
        self.weights = np.zeros(num_weights + 1)
        self.activation_function = activation_function
        self.learning_rate = learning_rate

    def fit(self, X: np.array, y: np.array): # X is 3-d array, y is 2-d array with batch size in first dimension
        updates = []
        for X_batch, y_batch in zip(X, y):
            assert X_batch.shape[0] == y_batch.shape[0]
            y_pred_batch = []
            for example, y in zip(X_batch, y_batch):
                print(example)
                example = np.append(example, 1)
                y_bar = self.predict(example)
                update = self.learning_rate * (y - y_bar) * example
            update = self.learning_rate * (X_batch.T * (y_batch - y_pred_batch)).T
            updates.append(update)

        print(update)
        self.weights = self.weights + np.sum(update(axis=1))

    def predict(self, example: np.array):
        return self.activation_function(self.weights.T @ example)

In [55]:
 (np.ones((3, 4)).T * np.array([1, 0, 1])).T

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [62]:
# unit tests

clf = Perceptron(4, step_function)
x = np.array([[[1, 2, 3, 1], [2, 3, 4, 1], [2, 3, 4, 1]], [[5, 6, 7, 1], [8, 9, 10, 1], [2, 3, 4, 1]]])
y = np.array([[1, 0, 1], [0, 0, 1]])

clf.fit(x, y)

[1 2 3 1]
[2 3 4 1]
[2 3 4 1]
[5 6 7 1]
[ 8  9 10  1]
[2 3 4 1]
[[-0.5 -0.6 -0.7 -0.1]
 [-0.8 -0.9 -1.  -0.1]
 [ 0.   0.   0.   0. ]]


TypeError: 'numpy.ndarray' object is not callable

# HW 3b

1. Repeat above but use one layer of 128 ReLU hidden units & backprop
2. Use Sigmoid as the activation function for the output
3. If maxEpochs = 10,000 runs too slowly, use 5,000 or 1,000
4. Optional: try #HUs in {16, 32, 64, 128, 256, 512, 1024, …, YouChooseMax} and use the best #HUs + stopping epoch on tune set per train-test fold
5. Compare to results discussed in HW3a